services:
  backend:
    image: ghcr.io/tijmensosef/federated-gateway-backend:latest
    ports:
      - "8080:8080"

  frontend:
    image: ghcr.io/tijmensosef/federated-gateway-frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - backend
