routes:
  - id: test-test-test-route
    uri: /hello
    upstream_id: 1
    plugins:
      limit-count:
        count: 2
        time_window: 60
        rejected_code: 503
        policy: local
      response-rewrite:
        status_code: 200
        body: |
          hello
      prometheus: {}
  - id: host-test-test-route
    uri: /world
    upstream:
      nodes:
        httpbin:80: 1
      type: roundrobin
    plugins:
      response-rewrite:
        status_code: 200
        body: |
          hello world
      prometheus: {}
  - id: veiligheidenvergunningen-test-test-route
    uri: /secure-test
    upstream_id: 1
    plugins:
      key-auth: {}
# parsed
upstreams:
  - id: 1
    nodes:
      httpbin:80: 1
    type: roundrobin
services:
  - id: 1
    upstream_id: 1
    plugins:
      limit-count:
        count: 1
        time_window: 60
        rejected_code: 503
      prometheus: {}
consumers:
  - username: jacks
    plugins:
      key-auth:
        key: auth-one
  - username: rose
    plugins:
      basic-auth:
        username: rose
        password: rose-password
global_rules:
  - id: 1
    plugins:
      limit-count:
        count: 100
        time_window: 60
        rejected_code: 503
        key: remote_addr
      prometheus: {}
#END