apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-frankgateway-config
data:
  apisix.yaml: |
{{ .Files.Get "files/apisix.yaml" | indent 4 }}
  config.yaml: |
    apisix:
      enable_control: true
      control:
        ip: "0.0.0.0"
        port: 9092
      enable_admin: false
    deployment:
      role: data_plane
      role_data_plane:
        config_provider: yaml
    plugins:
      - prometheus
    plugin_attr:
      prometheus:
        export_uri: /apisix/prometheus/metrics
        export_addr:
          ip: "0.0.0.0"
          port: 9091
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frankgateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-frankgateway
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-frankgateway
    spec:
      containers:
        - name: apisix
          image: {{ .Values.frankgateway.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: 9080
            - containerPort: 9091
            - containerPort: 9092
          volumeMounts:
            - name: config
              mountPath: /usr/local/apisix/conf/apisix.yaml
              subPath: apisix.yaml
            - name: config
              mountPath: /usr/local/apisix/conf/config.yaml
              subPath: config.yaml
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-frankgateway-config
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frankgateway
spec:
  type: LoadBalancer
  selector:
    app: {{ .Release.Name }}-frankgateway
  ports:
    - name: http
      port: {{ .Values.frankgateway.port }}
      targetPort: 9080
    - name: metrics
      port: 9091
    - name: control
      port: 9092
