apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
    scrape_configs:
      - job_name: apisix
        metrics_path: /apisix/prometheus/metrics
        static_configs:
          - targets: ["{{ .Release.Name }}-frankgateway:9091"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-prometheus
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-prometheus
    spec:
      containers:
        - name: prometheus
          image: {{ .Values.prometheus.image }}
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus/prometheus.yml
              subPath: prometheus.yml
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-prometheus-config
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-prometheus
spec:
  selector:
    app: {{ .Release.Name }}-prometheus
  ports:
    - port: 9090
