frankgateway:
  image: ghcr.io/wearefrank/frank-gateway:master
  port: 9080

prometheus:
  image: prom/prometheus:v3.4.0

console:
  image: ghcr.io/wearefrank/federated-gateway-console:latest
  port: 8080
